### ISSUE TITLE
how to add extensions?

### ISSUE THREAD

**Issue by JeffreySarnoff** [piever/InteractBulma.jl#27]
There are widgets for Bulma at
https://wikiki.github.io/
https://github.com/Wikiki/bulma-extensions

How does one make them available and theme-sensitive through InteractBulma?

**Comment by piever** [comment]
Some extensions (the ones needed for Interact) are downloaded [here](https://github.com/piever/InteractBulma.jl/blob/master/deps/build.jl#L62) and then simply included in the scss used to make the theme [here](https://github.com/piever/InteractBulma.jl/blob/master/assets/main.scss), which means they become sensitive to the theming.

Unfortunately at the moment there really isn't a smooth way to include more extension, but you can dev the package, edit the two locations I linked with more extension (both in the download step and in the scss file) and rebuild: then the next time you use it, it will include them in the generated css. I'm not sure what's the clean way to expose this functionality.

**Comment by JeffreySarnoff** [comment]
ok -- clarity helps

**Comment by piever** [comment]
If you have some specific extensions in mind we can also consider whether they can be added to Interact by default.

**Comment by JeffreySarnoff** [comment]
ok .. that is a better plan
